### PR TITLE
prevents modal closure before data has loaded

### PR DESCRIPTION
**Pull request by melugas**
adds condition to be met before modal close

### CODE REVIEW

**Comment by djbusstop** [comment]
Hey @melugas Thanks for getting started on that. I tried it in the testing branch (which is in the Github CI checks) and when I press esc too early, what happens it that it returns a blank page. I think we want to just do nothing in case it's closed without any layers. But I think it's a good solution :)

**Comment by melugas** [comment]
@djbusstop Oh that was an oversight on my end, sorry. I did not account for pressing the esc button at all - this pr only addresses onClick behavior of the X to close the modal. Let me know if you want me to address pressing esc/add a check or if you prefer I close the pr

**Comment by djbusstop** [comment]
@melugas Were you able to trigger the bug by clicking the X? If that wasn't an issue that was happening, I think it wasn't about the X but more about the esc? I am not sure. But if you couldn't recreate the bug then we don't have to fix it :)

**Comment by melugas** [comment]
closing pr- could not reproduce error.

**Pull request closed without merging**
