### PR TITLE
WIP - Search Bar Refactor - DO NOT MERGE

### PR DESCRIPTION
**Pull request by timhitchins**
Starting a PR for the search bar refactor so we can discuss.  It is hooked up to bing now but you will need an API key (dm on Slack).  Since this is a rebuild, we should probably discuss improving how we handle the bing returns.   

Current status:
- hooked up a debounced onChange input
- response is dispatched to store

To Do:
- parse through returned json to get list list to be rendered 
- build carto queries based on return **OR** render a popup based on lat/lon and query that way 

cc @djbusstop @benjaminben @isthewhiz

### CODE REVIEW

**Comment by jimboweb** [comment]
Hey everyone, I wanted to let you know I'm working on this.

**Comment by timhitchins** [comment]
Glad you are picking this up @Jim Stewart <jimboweb@gmail.com> ! Sorry I
just left it sitting here. Lmk if you have questions. This implementation
is denounced and currently only drops a point icon for any search.  The
current icon is the rent strike icon but could be switched out for
something else.  It does not trigger an info window event the way your
previous implementation did. Arrows and tabs should be working too. Happy
to jump on a call to discuss if that helps.

**Comment by djbusstop** [comment]
I merged the latest master and fixed any merge conflicts :+1:

**Comment by djbusstop** [comment]
Used this work as the basis for anothe

**Pull request closed without merging**
